//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemKaryawan
{
    using System;
    using System.Collections.Generic;
    
    public partial class karyawan
    {
        public string Id { get; set; }
        public string nama { get; set; }
        public string jabatan { get; set; }
        public string divisi { get; set; }
        public string hak { get; set; }
    }
}
